
server:
  port: 8081

spring:
  application:
    name: CreditCardService
  redis:
    database: 0
    host: localhost
    timeout: 8000
    port: 6379
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/creditcard?characterEncoding=UTF-8&useSSL=false
    username: root
    password:
    hikari:
      minimum-idle: 15
      auto-commit: true
      idle-timeout: 600000
      maximum-pool-size: 15
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: creditcarddb

mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis.cfg.xml