
server:
  port: 8081

spring:
  application:
    name: CreditCardService
  redis:
    database: 0
    host: ${REDIS_HOST}
    timeout: 8000
    port: ${REDIS_PORT}
  datasource:
    url: ${MYSQL_DB_URL}
    username: ${MYSQL_DB_USER}
    password: ${MYSQL_DB_PWD}
    hikari:
      minimum-idle: 15
      auto-commit: true
      idle-timeout: 600000
      maximum-pool-size: 15
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: creditcarddb

mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis.cfg.xml